### ISSUE TITLE
Correct link to documentation is in README.md?

### ISSUE THREAD

**Issue by bsr** [forcedotcom/lwc-dev-server-feedback#104]
I'd like to be able to read the documentation for the LWC dev server but the url for it in this repo's README.md file (https://developer.salesforce.com/tools/vscode/articles/lwc/localdev) redirects to https://developer.salesforce.com/tools/vscode/en/lwc/localdev which is a 404.

Going to the "All Documentation" (https://developer.salesforce.com/docs/) from the top nav on that page doesn't appear to have the relevant LWC dev server documentation on it.

What is the correct link to the documentation? Could it be added to the README.md file?

thanks,
Brent

**Comment by ekapner** [comment]
Thanks for reporting this issue. We rearchitected the docs and we'll look into fixing the 404s. The correct new link is: https://developer.salesforce.com/tools/vscode/en/localdev/lwclocaldev

**Comment by ekapner** [comment]
Fixed and merged.
