### ISSUE TITLE
Setting "port" in configuration file is not working

### ISSUE THREAD

**Issue by ndrewr** [forcedotcom/lwc-dev-server-feedback#11]
Setting the "port" key in `localdevserver.config.json` to something like `8008` still results in the server coming up at port `3333`.

Using the command line flag:
```
sfdx force:lightning:lwc:start -p 8008
```

works as expected however.

**Comment by KrisGraySFDC** [comment]
Work filed: @W-6746051

**Comment by lcampos** [comment]
This was fixed as part of release 2.1.0 and above. Thanks for opening this issue.
