### ISSUE TITLE
installation of @salesforce/lwc-dev-server downgrades sfdx-cli during update

### ISSUE THREAD

**Issue by jayree** [forcedotcom/lwc-dev-server-feedback#117]
**Describe the bug**
Installation of @salesforce/lwc-dev-server downgrades sfdx-cli during update

**To Reproduce**
```
❯ sfdx plugins:install @salesforce/lwc-dev-server
Successfully validated digital signature for @salesforce/lwc-dev-server.
Finished digital signature check.
Installing plugin @salesforce/lwc-dev-server... installed v2.10.0
❯ sfdx update
sfdx-cli: Updating CLI from 7.104.0 to 7.94.3-a4e7c7955b... done
sfdx-cli: Updating CLI... done
warning "@salesforce/lwc-dev-server > @rollup/plugin-alias@3.1.2" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
warning "@salesforce/lwc-dev-server > request-promise-native@1.0.9" has unmet peer dependency "request@^2.34".
warning "@salesforce/lwc-dev-server > request-promise-native > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
sfdx-cli: Updating plugins... done
```

**Expected behavior**
sfdx-cli stays on current version

**Desktop (please complete the following information):**
 - OS: Mac OS

**Comment by conni242** [comment]
Issue still causes problems: 

` sfdx update
sfdx-cli: Updating CLI from 7.108.0 to 7.94.3-a4e7c7955b... ⣻ 23.1 MB/51.1 MB
^C

❯ sfdx plugins:uninstall @salesforce/lwc-dev-server
Uninstalling @salesforce/lwc-dev-server... done

❯ sfdx update
sfdx-cli: Updating CLI from 7.108.0-d2f9bbd to 7.116.2-7d0f61b... done
sfdx-cli: Updating CLI... done
`

**Comment by benjaminloerincz** [comment]
@jayree @con242 I think this error does not occur anymore, right?
