### ISSUE TITLE
Add support for components that extend BasePrechat

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/lwc-dev-server-feedback#124]
**Is your feature request related to a problem? Please describe.**
I have a Pre Chat component that extends the BasePrechat and I can't run it on the Dev Server. 

````js
import BasePrechat from 'lightningsnapin/basePrechat';
export default class preChat extends BasePrechat {
...
}
````

**Describe the solution you'd like**
Create a way to locally simulate derived Chat components. 

**Describe alternatives you've considered**
I have to deploy the component to Salesforce to test. It is really painful.

**Additional context**
N/A

**Comment by AllanOricil** [comment]
Up

**Comment by Andries-Neyens** [comment]
is the casing correct?

`
import BasePrechat from 'lightningsnapin/BasePrechat';
import { api, track } from 'lwc';
`

**Comment by AllanOricil** [comment]
@Andries-Neyens no idea. When I tried it did not work. Maybe it is working now.
