### ISSUE TITLE
Unable to import the apex class from lwc js

### ISSUE THREAD

**Issue by rcsaravananmkd** [forcedotcom/lwc-dev-server-feedback#13]
Got error like Unknown scope, cannot resolve dependency .
![image](https://user-images.githubusercontent.com/28592634/66288870-8d336580-e8f8-11e9-8337-c5f9c3c3ec92.png)

**Comment by mysticflute** [comment]
I believe this is a bug with underscores being in the Apex class name. This will be fixed, but in the meantime if you remove the underscore then it will get you past this error.

**Comment by rcsaravananmkd** [comment]
Thanks , its working fine after removing the underscore from apex class.
But i unable to retrieve the records using soql from apex class . 
Even i have tried with recipes app also , records retrieve from a-ex class not rendered in local server page.

**Comment by mysticflute** [comment]
Which recipes component have you tried that isn't working?
