### ISSUE TITLE
sfdx plugins:install @salesforce/lwc-dev-server Error

### ISSUE THREAD

**Issue by sakthivelsfdc** [forcedotcom/lwc-dev-server-feedback#15]
Hi Team,

Received the following error when installing the lwc-dev-server plugins.

C:\Workspace\SakthiDevOrg\TechforceLWCLocal\TechforceLWC>sfdx plugins:install @salesforce/lwc-dev-server
Error: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established

![VS_Code_Error1](https://user-images.githubusercontent.com/45456876/66357386-59b90f80-e9ba-11e9-87fb-5a98ad1dc899.PNG)

**Comment by sakthivelsfdc** [comment]
But the same installation commented worked fine in my personal laptop and this is the my company network, so is there any proxy settings to enable?

**Comment by KrisGraySFDC** [comment]
This should be based on your company network settings.

Heres documentation on it.
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm

**Comment by ntotten** [comment]
This is likely a proxy issues. Unfortunately, proxy issues are something you will have to work with your IT department on.
