### ISSUE TITLE
Unable to install lwc-dev-server / run sfdx force:lightning:lwc:start

### ISSUE THREAD

**Issue by pravinsable** [forcedotcom/lwc-dev-server-feedback#150]
I am trying to run LWC in local. I was able to install with errors

C:\WINDOWS\system32>sfdx plugins:install @salesforce/lwc-dev-server
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/lwc-dev-server.
Finished digital signature check.
Installing plugin @salesforce/lwc-dev-server... - [2/4] Fetching packages...
warning "@salesforce/lwc-dev-server > request-promise-native@1.0.9" has unmet peer dependency "request@^2.34".
warning "sfdx-plugin-source-read > @salesforce/command > @oclif/test > @oclif/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "sfdx-plugin-source-read > @salesforce/command > @oclif/test > @oclif/core > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
Installing plugin @salesforce/lwc-dev-server... - [4/4] Building fresh packages...
(node:14016) TypeError Plugin: @salesforce/lwc-dev-server: Cannot read properties of undefined (reading 'prototype')
module: @oclif/core@2.6.2
task: toCached
plugin: @salesforce/lwc-dev-server
root: C:\Users\xxxx\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server
See more details with DEBUG=*
Installing plugin @salesforce/lwc-dev-server... installed v2.11.0

while running I am getting following error.

C:\WINDOWS\system32>sfdx force:lightning:lwc:start
(node:20104) TypeError Plugin: @salesforce/lwc-dev-server: Cannot read properties of undefined (reading 'prototype')
module: @oclif/core@2.6.2
task: toCached
plugin: @salesforce/lwc-dev-server
root: C:\Users\xxxx\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server
See more details with DEBUG=*
Is local development even supported in March 2023? Looks like abandoned project but would love to get some confirmation from Salesforce.

**Comment by zerkz** [comment]
It's a beta product so there's never been full support. Check out the feedback issue created awhile back. See this thread from the last known correspondence on LWC server from Salesforce - https://github.com/forcedotcom/lwc-dev-server-feedback/issues/143
