### ISSUE TITLE
LWC unable to import another LWC, possible namespace issue.

### ISSUE THREAD

**Issue by scott-call** [forcedotcom/lwc-dev-server-feedback#20]
**Describe the bug**
Loading a LWC that references another LWC in its markup results in an error:

> [0] [rollup] 'c/sampleLWC' is imported by force-app/main/default/lwc/anotherLWC/anotherLWC.js, but could not be resolved – treating it as an external dependency

Both LWCs are in the same **project/force-app/main/default/lwc** directory. Our package will be a managed package with a namespace, but is currently unreleased. I've tried adding the namespace to the **localdevserver.config.json**, but it does not change the results.
`{
  "namespace": "ourSampleNamespace"
}`

**To Reproduce**
1. Start lwc-dev-server.
2. Click on a LWC that references another LWC in its markup.
3. Observe error, for example:
![image](https://user-images.githubusercontent.com/37962980/66609842-443d1480-eb77-11e9-8a04-a6a42bb92ff4.png)
4. Observe error in lwc-dev-server terminal window, for example:
> [0] [rollup] 'c/packetBuilderPacketSelectorModal' is imported by force-app/main/default/lwc/packetBuilder/packetBuilder.html, but could not be resolved – treating it as an external dependency

**Expected behavior**
The selected LWC loads with its dependent LWCs.

**Desktop (please complete the following information):**
 - macOS Mojave v10.14.6
 - Chrome v77

**Comment by xialisun** [comment]
I am facing the same issue. @scott-call  have you find any work around?

**Comment by lcampos** [comment]
This issues is fixed in release 2.4.0, thanks for providing feedback.
