### ISSUE TITLE
Changes to static resources aren't rebuilt to .localdevserver

### ISSUE THREAD

**Issue by gbreavin** [forcedotcom/lwc-dev-server-feedback#22]
**Describe the bug**
If I edit a static resource in a project folder, there is activity in the terminal, and the browser refreshes. However, the change is not reflected in the browser, because the files in the .localdevfolder are not rebuilt.

**To Reproduce**
Requires a component that uses a static resource - I used an image.

1. Load the component on the local dev server
2. Make a change to the static resource that will result in a change that can be seen in the browser - for example, if the resource is an image, modify the image contents
3. Wait for the browser to refresh
4. Note that the change is not reflected
5. Look at the static resource in the .localdevserver - note that the 

**Expected behavior**
The file should be rebuilt to the .localdevserver folder so that when the browser refreshes, changes are shown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome

**Additional context**
Possible dupe of #4 ?

**Comment by JimmyBarzmark** [comment]
I have the same issue.

When loading a static resource css with loadStyle(); changes to the css do not take effect until the localhost:3333 is stopped and re-launched. This defeats the purpose of the hot reload.

 - OS: Windows 10
 - Browser All
 - Version N/A

**Comment by sfsholden** [comment]
Closing. This feature has been implemented as part of release 2.8.0. 

Note that file changes will cause a reload, however file additions and deletions from the static resources folder will still not cause a reload of the project at this time. However, there are workarounds that do not require a restart of the server.

Workarounds:
1) Any edit to a .js or .html file from within the component should cause a recompilation, which will regenerate the static resources.
2) Disable browser cache. Here is an example of what this would look like from Google Chrome - https://www.technipages.com/google-chrome-how-to-completely-disable-cache.
