### ISSUE TITLE
Was not able to run the Local Dev server

### ISSUE THREAD

**Issue by miteshmsharma** [forcedotcom/lwc-dev-server-feedback#31]
**Describe the bug**
While trying to install the LWC local server following the instructions mentioned on https://developer.salesforce.com/tools/vscode/articles/lwc/localdev

I encountered following error -

Error: yarn add @salesforce/lwc-dev-server@latest --non-interactive --mutex=file :C:/Users/Dell/AppData/Local/sfdx/yarn.lock --preferred-cache-folder=C:/Users/De ll/AppData/Local/sfdx/yarn --check-files exited with code 1 at ChildProcess.forked.on (C:/Users/Dell/AppData/Local/sfdx/client/7.21.0-96 4f56bd1a/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)

Please let me know if there is anything I could do to resolve this issue?
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mysticflute** [comment]
Are you still seeing this issue with the latest version? If so, is there an additional error message below this line?
