### ISSUE TITLE
pubsub is not working

### ISSUE THREAD

**Issue by monirkohi2006** [forcedotcom/lwc-dev-server-feedback#42]
**Describe the bug**

**To Reproduce**
1. Create two LWC components. 
2. Subscribe the first component to an event.
3. Fire an event from the second component. 
4. The first component is not capturing the event. 

**Expected behavior**
The component that is registered to the event should handle the event when the event is fired from another component. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 78.0.3904.87

**Additional context**
This is working in the Sandbox.

**Comment by mysticflute** [comment]
@monirkohi2006 can you please share the code you were using to subscribe and to fire the event?
