### ISSUE TITLE
emp API does not work

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/lwc-dev-server-feedback#45]
**Describe the bug**
I have work components on my salesforce playgroun using empApi. When I load them locally I get the following errors. There are two different components doing two different things but both using empApi and both working when running on a Scratch org.

![image](https://user-images.githubusercontent.com/55927613/69755711-be8a1e00-1150-11ea-8a96-c039454dc27e.png)

![image](https://user-images.githubusercontent.com/55927613/69755727-cb0e7680-1150-11ea-87a1-758c1099d081.png)

**Comment by KrisGraySFDC** [comment]
Pretty sure that it is listed in the known set of components that we do not expect to work. We have not provided the code for it to run locally as it currently does not have the APIs needed for it to work locally.
