### ISSUE TITLE
Wire not working

### ISSUE THREAD

**Issue by juvian** [forcedotcom/lwc-dev-server-feedback#46]
Component:
   ```
 import getListingTypesBySite from '@salesforce/apex/List_BuyBox_Item.getListingTypesBySite';
    @wire(getListingTypesBySite, {})
    listingTypeInfo({data, error}) {
        if (data) this.listing_types = data;
    }
```

Apex: 

```
public class List_BuyBox_Item {
    @AuraEnabled(cacheable=true)
    public static Map<String, Map<String, String>> getListingTypesBySite() {
         Map<String, Map<String, String>> listingTypes = new Map<String, Map<String, String>>();
         
         for (Listing_Type__c listing : [SELECT 
                                                        Name__c,
                                                        ML_ID__c,
                                                        Site_Id__c 
                                                FROM
                                                        Listing_Type__c
                                                WHERE
                                                        Inactive__c = False
                                                ]) {
             if (listingTypes.containsKey(listing.site_id__c) == false) listingTypes.put(listing.site_id__c, new Map<String, String>());
             listingTypes.get(listing.site_id__c).put(listing.ml_id__c, listing.name__c);
         }
         
         return listingTypes;
    }
}
```

Response from http://localhost:3333/api/apex/execute: 500 internal error -> error parsing or finding aura config: window.Aura not found

Does wire not work from local development?

**Comment by KrisGraySFDC** [comment]
Wire is intended to work.
Can you include some information here for us?
 - Is this on a pre-release org?
 - Is it still happening? Can you login to your scratch org and see the Lightning homepage with no issues?
 - Assume this will still happen when the method returns static data, can you verify?

Thanks

**Comment by juvian** [comment]
It is not a pre-release org, but it is not a scratch org either. Lightning is not yet enabled and I'm using components inside visualforce with lightning out. I can see that in the visualforce, after including the lightning out.js script there is a window.Aura property, but in the local environment there is not.

I can test on monday if it works fine in the visualforce, if it doesn't work either I guess auraenabled methods might not work with lightning out.

**Comment by KrisGraySFDC** [comment]
That explains it. If Lightning isn't enabled, we won't be able to make requests via Apex. Thats not a requirement of the framework, just a limitation of the LWC Local Dev Beta implementation.

**Comment by KrisGraySFDC** [comment]
Also, because data modifications will happen against the org you're connected to, we encourage you not to use real orgs to test against.

**Comment by juvian** [comment]
I see, good to know. Will try enabling lightning then. And yeah, its a development org. Thanks!

**Comment by KrisGraySFDC** [comment]
Your welcome.
