### ISSUE TITLE
lwc-dev-server has incorrect peer dependency "@lwc/engine@1.0.x"

### ISSUE THREAD

**Issue by iandrosov** [forcedotcom/lwc-dev-server-feedback#49]
I am getting this error while update SFDX lwc-dev-server
warning "@salesforce/lwc-dev-server > @webruntime/compiler > @lwc/rollup-plugin@1.0.2-222.18" has incorrect peer dependency "@lwc/engine@1.0.x"

My node version: v10.16.0
SFDX CLI version: sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

**Comment by KrisGraySFDC** [comment]
Thank you! I think its just a warning, and we're working to address it in an update next week.

**Comment by KrisGraySFDC** [comment]
We delayed the part of the update which would have addressed the warning. Thanks for reporting it, we're still trying to squash it.

**Comment by AltiusRupert** [comment]
Hi @KrisGraySFDC, better hurry up : LWC local dev was announced at the Release Readiness webinar last week ;)
Good luck

**Comment by KrisGraySFDC** [comment]
Updates are happening to enable it, it's going to be beautiful.

**Comment by amansaw** [comment]
@KrisGraySFDC - Got the same issue while I did updated lwc server plugin today. Is there any fix for this one ?

**Comment by amansaw** [comment]
Whenever the server starts and I want to go to my components, this is the page that I see with no link whatsoever. A simple page without any navigation to lwc components.
![image](https://user-images.githubusercontent.com/12405646/83493257-22abe700-a4d2-11ea-84ca-96dc9ecd1304.png)

**Comment by Doondireddy** [comment]
@KrisGraySFDC I too have the same blank page as @amansaw ,

When I Inspect the page, this is the output. 

![lwc_Error](https://user-images.githubusercontent.com/38418517/83526686-6ddeed80-a504-11ea-908c-80bb252fb7d1.jpg)

**Comment by lcampos** [comment]
This was fixed in release `2.1.0` and above. Thanks for reporting this.
