### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Pawans2** [forcedotcom/lwc-dev-server-feedback#50]
When I am running sfdx "plugins:install @salesforce/lwc-dev-server" command getting "Error: unable to get local issuer certificate" error.

**Comment by KrisGraySFDC** [comment]
Were you able to resolve this issue?

**Comment by Pawans2** [comment]
No, still not working. Tried many times but getting same error.

Thanks,
Pawan

**Comment by KrisGraySFDC** [comment]
I think it generates a log, is there any more information you can send along?
