### ISSUE TITLE
 Warning: force:lightning:lwc:start is not a sfdx command.

### ISSUE THREAD

**Issue by sfdcocean** [forcedotcom/lwc-dev-server-feedback#52]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mysticflute** [comment]
Hi,

Can you please confirm that the plugin has successfully installed by running ` sfdx plugins`? It should show @salesforce/lwc-dev-server. If it doesn't then please follow the setup instructions here https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.get_started_local_dev_setup

**Comment by aetto** [comment]
I'm getting the same problem.
the installation of the plugin fails.
Here's the log.

> `Ashwins-MacBook-Pro:bretto.devhub.lwc aetto$ sfdx plugins:install @salesforce/lwc-dev-server
> Debugger listening on ws://127.0.0.1:55562/bddd672e-3fb1-4051-89bc-9c06957581fa
> For help, see: https://nodejs.org/en/docs/inspector
> Debugger attached.
> Successfully validated digital signature for @salesforce/lwc-dev-server.
> Finished digital signature check.
> Debugger listening on ws://127.0.0.1:55596/7677b96e-60e3-499a-b7d9-341ff5acc384
> For help, see: https://nodejs.org/en/docs/inspector
> Debugger attached.
> warning @salesforce/lwc-dev-server > cpx > chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> warning @salesforce/lwc-dev-server > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> warning @salesforce/lwc-dev-server > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> warning @salesforce/lwc-dev-server > @webruntime/compiler > rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
> warning @salesforce/lwc-dev-server > @webruntime/compiler > rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
> warning @salesforce/lwc-dev-server > @webruntime/compiler > rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.
> warning @salesforce/lwc-dev-server > cpx > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> warning @salesforce/lwc-dev-server > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning @salesforce/lwc-dev-server > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning @salesforce/lwc-dev-server > @webruntime/api > @lwc/compiler > rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.
> warning @salesforce/lwc-dev-server > cpx > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> warning @salesforce/lwc-dev-server > jsdom > request > har-validator@5.1.5: this library is no longer supported
> warning @salesforce/lwc-dev-server > cpx > chokidar > readdirp > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> warning @salesforce/lwc-dev-server > cpx > chokidar > readdirp > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> warning "@salesforce/lwc-dev-server > @rollup/plugin-alias@3.1.1" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
> warning "@salesforce/lwc-dev-server > request-promise-native@1.0.9" has unmet peer dependency "request@^2.34".
> warning "@salesforce/lwc-dev-server > request-promise-native > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
> warning Error running install script for optional dependency: "/Users/aetto/.local/share/sfdx/node_modules/cpx/node_modules/fsevents: Command failed.
> Exit code: 1
> Command: node install.js
> Arguments: 
> Directory: /Users/aetto/.local/share/sfdx/node_modules/cpx/node_modules/fsevents
> Output:
> Debugger listening on ws://127.0.0.1:55702/18ec5df3-2044-4964-8faf-bd9168c3e053
> For help, see: https://nodejs.org/en/docs/inspector
> Debugger attached.
> Waiting for the debugger to disconnect...
> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn node-gyp ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn node-gyp',
>   path: 'node-gyp',
>   spawnargs: [ 'rebuild' ]
> }"
> Installing plugin @salesforce/lwc-dev-server... ⣷ info This module is OPTIONAL, you can safely ignore this error
> Debugger listening on ws://127.0.0.1:55562/bddd672e-3fb1-4051-89bc-9c06957581fa
> For help, see: https://nodejs.org/en/docs/inspector
> Ashwins-MacBook-Pro:bretto.devhub.lwc aetto$ `

tried installing several times and facing the same issue.
