### ISSUE TITLE
Severe Performance Issue while using LWC Local Server

### ISSUE THREAD

**Issue by suresh83kumar** [forcedotcom/lwc-dev-server-feedback#55]
### Summary

Facing huge performance issue while using LWC local development server. Getting error like,
Error: The local development server exited unexpectedly with code 134.

### Steps To Reproduce:

1.  Make changes to your code and click Save.
1.  Take > 90 secs to reload the page and sometime throwing error like,
Error: The local development server exited unexpectedly with code 134.

### Expected result

Expected to work instantly where i see changes appear in localhost page.

### Actual result

Getting this error in command line output:
Error: The local development server exited unexpectedly with code 134.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:1.41.0

**SFDX CLI Version**: sfdx-cli/7.44.0-e77f9c8515 win32-x64 node-v10.15.3

**OS and version**: Windows_NT x 64 10.0.17763

**Comment by suresh83kumar** [comment]
Sorry I don’t have access to GUS orgs. Is this issue getting fixed?

**Comment by KrisGraySFDC** [comment]
Hi @suresh83kumar, we're not at the moment but when we do tackle this we'll need some information on what you're source is like. 

We have a lot of tests that verify this exact workflow and none of them are hitting this issue, so whats special about your setup? Is your code doing something fancy? Can you remove more and more code from the file thats causing this issue till its the one or two lines that are causing it?

**Comment by mysticflute** [comment]
@suresh83kumar are you still seeing this issue? If so can you please share additional information such as any other output from the console before it exits?

As for the 90 seconds, does this refer to the time it takes for the browser to refresh automatically or the time it takes to see your changes with a manual refresh?

**Comment by mysticflute** [comment]
@suresh83kumar please share if you are still seeing this issue?

**Comment by suresh83kumar** [comment]
Hi Nathan,

Let me retry and keep you updated.

Regards,
Suresh

**Comment by suresh83kumar** [comment]
@mysticflute - It is working fine now. I don't see performance issue.
