### ISSUE TITLE
Local development server unable to find custom components

### ISSUE THREAD

**Issue by morwalz** [forcedotcom/lwc-dev-server-feedback#59]
sfdx-project.json

``
{
  "packageDirectories": [
    {
      "path": "xyz",
      "default": true
    }
  ],
  "namespace": "xyz",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "45.0"
}
``
I am trying to use component from same package. 
`   <c-component-from-same-package></c-component-from-same-package>
`
and functions from same package 

`import {
    getContactsRequiredFields,
    proxyObjectConverter,
    setOrgChartContacts
} from "c/utility";` show errors unable to find the file or component. 
When i change c to package name then local development server work but i can not push the code to org as there is rule which only allow component with c-

**Comment by morwalz** [comment]
Anyone can help here ??
it is very critical to us.

**Comment by mysticflute** [comment]
@morwalz are your LWC components located under `xyz/main/default/lwc`? Also do you have a `localdevserver.config.json` file specified?

**Comment by morwalz** [comment]
Hi @mysticflute Yes, my LWC components are defined under xyz/main/default/lwc folder. 

And i have created localdevserver.config.json file. In this file I have added namespace as well.

**Comment by morwalz** [comment]
How can i see this what is mentioned in the work item ?

**Comment by lcampos** [comment]
Release 2.4.0 addresses this limitation. Thanks for opening this issue and providing feedback.
