### ISSUE TITLE
@track decorator

### ISSUE THREAD

**Issue by sf9y** [forcedotcom/lwc-dev-server-feedback#60]
@track decorator has been removed with Spring 20 release, but it seems that decorator is still needed for lwc local dev server as of today, April 27th 2020?

**Comment by mysticflute** [comment]
I assume you are referring to this? https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_lwc_track.htm

The `@track` decorator is not removed, but in most cases it is no longer needed. See the bottom of the above document for scenarios on when you may still need it.

Version `1.0.10` is on a Spring '20 version release of the LWC compiler. Are you running into a specific error message with usage or non-usage of `@track`? If so please share the error you are seeing.

**Comment by sf9y** [comment]
Thanks for the response. No, I was not getting any error with non-usage of @track, but when I don't use it the component is not reflecting any changes to the input. For example, I was trying the helloBinding component from lwc-recipes, when I am typing the greeting the ouput text is not showing the changed greeting. Whereas if I use the @track on the greeting variable, it is working as expected. Again, thanks for the followup.

**Comment by lcampos** [comment]
This was fixed in the latest releases (2.1.0 and above). Thanks for providing feedback.
