### ISSUE TITLE
configProvider.getCoreInfo is not a function

### ISSUE THREAD

**Issue by kamipatel** [forcedotcom/lwc-dev-server-feedback#65]
**Describe the bug**
Local web Server starts ok but on the web page it throws this error "configProvider.getCoreInfo is not a function"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lcampos** [comment]
This was fixed as part of the changes in version `2.1.0` and above. Thanks for reporting the issue.
