### ISSUE TITLE
Preview does not work - Api Version: 49.0

### ISSUE THREAD

**Issue by spyderdsn** [forcedotcom/lwc-dev-server-feedback#68]
Running SFDX Preview Component Locally in VS code show this error. in the browser. 

`Webruntime.moduleRegistry.define('webruntimegenerated/view__home', [], function() { var err = new Error(`Could not load lightning\/verticalNavigation (imported by \/Users\/someuser\/.local\/share\/sfdx\/node_modules\/@salesforce\/lwc-dev-server\/modules\/localdevserver\/componentsPanel\/componentsPanel.html): ENOENT: no such file or directory, open \'lightning\/verticalNavigation\'`);
err['message'] = `Could not load lightning\/verticalNavigation (imported by \/Users\/someuser\/.local\/share\/sfdx\/node_modules\/@salesforce\/lwc-dev-server\/modules\/localdevserver\/componentsPanel\/componentsPanel.html): ENOENT: no such file or directory, open \'lightning\/verticalNavigation\'`;
err['stack'] = `Error: Could not load lightning\/verticalNavigation (imported by \/Users\/someuser\/.local\/share\/sfdx\/node_modules\/@salesforce\/lwc-dev-server\/modules\/localdevserver\/componentsPanel\/componentsPanel.html): ENOENT: no such file or directory, open \'lightning\/verticalNavigation\'
    at \/Users\/someuser\/.local\/share\/sfdx\/node_modules\/rollup\/dist\/rollup.js:21718:19`;
throw err; } );`

**Comment by alide** [comment]
We have the same problem since last weekend. The preview works fine for the dev hub which API version is still 48.0. But not working for our sandbox which API version is 49.0.

**Comment by agnivesh29** [comment]
same here.

**Comment by lcampos** [comment]
Hi, thanks for opening this issue. The root cause is that there are some platform changes in the new release the broke the local experience. We are working on a fix that should be out soon and I'll make sure to update this thread once it's publicly available. Sorry for the inconvenience and disrupting your workflow.

**Comment by lcampos** [comment]
Hi, the fix is now available under version `2.1.0` of the plugin. You can run `sfdx plugins:update` or `sfdx plugins:install @salesforce/lwc-dev-server` to get the new version. Thanks for opening this issue and sorry for the inconvenience this caused.

**Comment by proogramer** [comment]
Thank you so much for resolving this issue. Localhost working fine right now...

Thank you again !!

**Comment by KimiEatsCode** [comment]
Thank you yes so very much. Our team is very grateful for the speediness in which this issue was resolved. Learning salesforce development for the first time in our lives without any git repo to depend on has made the local sever dev plugin invaluable. Thanks again!!
