### ISSUE TITLE
Local dev server throws error while loading messageChannel

### ISSUE THREAD

**Issue by sandeep-chilakala** [forcedotcom/lwc-dev-server-feedback#79]
**Describe the bug**
I have created a message channel and referring to the LWC component.

when I try to load the component I am getting the below error message.

Error loading http://localhost:3333/webruntime/component/latest/dev/en-US/@salesforce/messageChannel/MessageChannel-Name from http://localhost:3333/webruntime/custom-component/latest/dev/en-US/c/Component-Name

**To Reproduce**
1. Create a message channel.
2. Import message channel in LWC Component.
3. Open LWC Component in Local dev server.
4. Server throws an error

**Expected behavior**
Component should load

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Chrome

**Comment by msrivastav13** [comment]
Lightning Message Service (LMS) module is not supported at this point. Refer to the lwc docs to see which modules are supported and which ones are not!

Thank you
