### ISSUE TITLE
sfdx plugins:install @salesforce/lwc-dev-server

### ISSUE THREAD

**Issue by HariGit** [forcedotcom/lwc-dev-server-feedback#8]
Installing plugin @salesforce/lwc-dev-server... \ info There appears to be trouble with your network connection. Retrying...

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KrisGraySFDC** [comment]
Is this on your corporate network? A lot of them have proxies you need to setup.

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm

**Comment by couturecraigj** [comment]
This is not the case in my error.  Upon failing I get
`An unexpected error occurred: "https://registry.yarnpkg.com/core-js/-/core-js-2.6.10.tgz: ESOCKETTIMEDOUT".`
I then navigate to this address in my browser with no issue.  It also downloads the tgz file.  I would really love to start trying to use this.  Please actually check into what is happening.  I have no proxy setup and there is no issue with navigating to the given URL
