### ISSUE TITLE
LWC server errors on start with Unable to expose method "then"

### ISSUE THREAD

**Issue by CatJazz** [forcedotcom/lwc-dev-server-feedback#82]
Am I doing something wrong?  This was working for me several months ago.

0. node --version
   v12.18.3

1. sfdx update
   sfdx-cli: Updating CLI... already on latest version: 7.75.0-5521f40d11
   warning "@salesforce/lwc-dev-server > @rollup/plugin-alias@3.1.1" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
   warning "@salesforce/lwc-dev-server > request-promise-native@1.0.8" has unmet peer dependency "request@^2.34".
   warning "@salesforce/lwc-dev-server > request-promise-native > request-promise-core@1.1.3" has unmet peer dependency "request@^2.34".
   sfdx-cli: Updating plugins... done
   sfdx plugins
   @salesforce/lwc-dev-server 2.5.1
   ├─ @oclif/plugin-help 2.2.1
   └─ @oclif/plugin-update 1.3.9
   salesforcedx 49.13.0
   ├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
   ├─ templates 49.10.0
   ├─ custom-metadata 1.0.10
   ├─ salesforce-alm 49.12.1
   └─ apex 0.1.0

2. sfdx force:lightning:lwc:start
   Error: Unable to expose method "then"

**Comment by xyc** [comment]
@CatJazz Could you try the following workarounds?
1. Uninstalled local dev plugins & re-install it. If you are using npm based cli, try the standalone executable.
2. Try starting local dev server with `SFDX_LAZY_LOAD_MODULES=false` flag: `SFDX_LAZY_LOAD_MODULES=false sfdx force:lightning:lwc:start`

**Comment by CatJazz** [comment]
I tried @xyc but still get same error.

**Comment by Chris-James** [comment]
While attempting to follow [these instructions](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.get_started_local_dev_setup) I received the same error:
```bash
$ sfdx force:lightning:lwc:start
    Error: Unable to expose method "then"
```
However, in my case, setting `SFDX_LAZY_LOAD_MODULES` false as per @xyc's [comment](https://github.com/forcedotcom/lwc-dev-server-feedback/issues/82#issuecomment-713911471) worked:
```
$ SFDX_LAZY_LOAD_MODULES=false sfdx force:lightning:lwc:start

Starting LWC Local Development.
    Dev Hub Org: <...>
    Scratch Org: <...>
    Api Version: 50.0
```

**Comment by CatJazz** [comment]
Thanks @Chris-James.  It is working now for me.  Issue was my scratch org was expired, but I still got the same error as you.  Only if I tried running command in a bash shell did I get a warning about the invalid scratch org.
