### ISSUE TITLE
Navigation Mixin does not work

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/lwc-dev-server-feedback#86]
### Description

I opened this issue on the LWC repo, but it seems it belongs to this repo. https://github.com/salesforce/lwc/issues/2073

I tried to use the navigaton example from the official docs, as it is, and it didn't work. On the local development server this example throws an error, while inside salesforce it does not throw anything.

https://developer.salesforce.com/docs/component-library/bundle/lightning-navigation/documentation

#### Steps to Reproduce

Create a LWC component with a button.

````html
<template>
<button onclick={onClickNavigationButton}>Go to Account Home</button>
</template>
````

````javascript
import { LightningElement } from "lwc";
import { NavigationMixin } from 'lightning/navigation';

export default class TestComponent extends LightningElement {

  onClickNavigationButton(){
    this[NavigationMixin.Navigate]({
      type: 'standard__objectPage',
      attributes: {
          objectApiName: 'Account',
          actionName: 'home',
      },
    });
  }
}
`````

or

````javascript
import { LightningElement } from "lwc";
import { NavigationMixin } from 'lightning/navigation';

export default class TestComponent extends LightningElement {

  onClickNavigationButton(){
    this[NavigationMixin.Navigate]({
      type: 'standard__objectPage',
      attributes: {
          objectApiName: 'Account',
          actionName: 'new',
      },
    });
  }
}
`````

#### Expected Results
It should send the user to the account home page or new page

#### Actual Results
on Local development server it throws this exception

![image](https://user-images.githubusercontent.com/55927613/97784852-5b431000-1b99-11eb-902f-bb10095189fd.png)

on Salesforce org it does not throw any error and it does not navigate the user to anywhere.

### Browsers Affected
Tested only on Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by msrivastav13** [comment]
NavigationMixin is not supported in the local development server. There are some modules the local development server does not support at this point!

**Comment by AllanOricil** [comment]
@msrivastav13 where can I open an Issue regarding the other problem of the navigation mixin not working even inside Salesforce? I copied and pasted the example from the docs and it did not work.

**Comment by msrivastav13** [comment]
@AllanOricil I suggest you first use a platform like https://salesforce.stackexchange.com/ to post a query on what is not working with the code.

You can also open a support case with Salesforce Support!

**Comment by msrivastav13** [comment]
Looking at the code you have it wrong, where did you copy the code from?

Make sure your class extends NavigationMixin  and passes LightningElement  as shown below

`export default class MyCustomElement extends NavigationMixin(LightningElement) {}
`

The above will work in Salesforce org but not in the local dev server as it is not supported yet!

**Comment by AllanOricil** [comment]
@msrivastav13 thanks for noticing that
