### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/lwc-dev-server-feedback#87]
**Is your feature request related to a problem? Please describe.**
Yes, eslint is not indicating what is the problem with my component, and neither the console or the dev server messages are saying anything. There is no way for me to find where it is wrong.

![image](https://user-images.githubusercontent.com/55927613/98944255-af7ab800-24e8-11eb-8fa7-6698b00e60b1.png)

![image](https://user-images.githubusercontent.com/55927613/98944415-ea7ceb80-24e8-11eb-83b8-3428cb11042f.png)

**Describe the solution you'd like**
Enable source maps by default.

**Comment by lcampos** [comment]
Thanks for opening this issue @AllanOricil. We made some changes that provide accurate error information when previewing a component in version 2.6.0. I'll close this issue since it's been fixed.

**Comment by AllanOricil** [comment]
@lcampos 
I'm still seeing non helpful error messages

![image](https://user-images.githubusercontent.com/55927613/99968932-b7ace000-2d91-11eb-96a7-41d0fc62ef4a.png)

**Comment by AllanOricil** [comment]
I understood the problem. It was a typo in the component's name that I was referencing from inside the `test` component.
You could add a message saying "We can't find the component Foo that is referenced inside the component Bar."
