### ISSUE TITLE
Dev server can only work with one project folder at the time

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/lwc-dev-server-feedback#88]
**Describe the bug**
I have a package with 2 folders "force-app-1" and "force-app-2". Both have lwc components, but the dev server only shows the components from the first folder.

**To Reproduce**
1 - Create another project folder inside the same sfdx project.
2 - Create a lwc component inside this other folder.
3 - Start the dev server
4 - Verify that only the components from the main folder are being displayed

**Expected behavior**
Dev server should show all the lwc components within a sfdx project.

**Comment by JackVeromeev** [comment]
is there any update?

**Comment by sanjaykharwar** [comment]
> This issue has been linked to a new work item: W-8483544

Any update on this work item?

**Comment by ytiq** [comment]
any updates?
