### ISSUE TITLE
Lightning Card is not rendering the borders locally

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/lwc-dev-server-feedback#9]
**Describe the bug**
Lightning Card does not display properly locally. Locally the card is not rendering the borders.

![image](https://user-images.githubusercontent.com/55927613/66259412-a3321080-e7a8-11e9-89d2-2c2acacf24bc.png)

In an Org it renders everything properly.
![image](https://user-images.githubusercontent.com/55927613/66259417-b5ac4a00-e7a8-11e9-8a96-7f2b3a494aa3.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 - Version Last Version

**Comment by mysticflute** [comment]
This is probably because in SLDS, the borders on cards within other cards are hidden (the preview page container is also an slds-card).
