### ISSUE TITLE
Unable to get Sandbox Data to LWC Local Server Component Preview

### ISSUE THREAD

**Issue by navinselvaraj** [forcedotcom/lwc-dev-server-feedback#90]
When I connected my lwc project in vs code to my sandbox, I am unable to pull the data from sandbox org to my local lwc component preview.
But, I can able to get the sandbox data from only one sandbox. When i connected to different sandbox, I am unable to get the sandbox data to the local preview.
Please let me know why lwc local is behaving like this of different sandboxes. Did I missing anything? When i connect the same component to developer org, it is working perfectly.
Thanks in advance for your help.

**Comment by trinasfdx** [comment]
@navinselvaraj We fixed this in one of the latest releases. Try it out!
