### ISSUE TITLE
Upon Startup LWC Dev Server presents a blank screen for localhost:[Port]

### ISSUE THREAD

**Issue by sfsholden** [forcedotcom/lwc-dev-server-feedback#91]
**Describe the bug**
With the latest release of the LWC Dev Server, there is a known issue where upon loading `http://localhost:3333/` (or substitute with custom port), the user is presented with a blank screen. Please note that we are actively working on this issue. If this affects you, please let us know. We are still trying to determine how to consistently reproduce the issue.

**Workaround**
Restart local dev server.

**Version**
2.6.0

**To Reproduce**
Steps to reproduce the behavior: Unknown.

**Expected behavior**
Should load the preview page with components.

**Actual behavior**
Blank screen appears. Console logs show errors. This goes away by restarting the local dev server.

**Screenshots**
![Screen Shot 2020-11-16 at 3 47 37 PM](https://user-images.githubusercontent.com/45604118/99320279-862f9400-2828-11eb-9f49-c11b5b77a03f.png)

**Comment by sfsholden** [comment]
This was resolved with https://github.com/forcedotcom/lwc-dev-server/pull/282. Closing.

**Comment by tleecode** [comment]
I'm having the same issue. How were you able to resolve this problem? Github link doesn't seem to work anymore
