### ISSUE TITLE
LocalDevServer doesn't render components that inherit from LightningElement

### ISSUE THREAD

**Issue by celador** [forcedotcom/lwc-dev-server-feedback#94]
### Summary

I have a base class `export default class StatedElement extends LightningElement` that is a LWC.  I have other components that extend that base component such as `export default class WidgetEnrichment extends StatedElement`   These components do not show in the LWC Dev Server, so none of my apps render.  :(

### Steps To Reproduce:

1.  Create a component (Component1)
2. Create another component (Component2) that extends Component1
3. Component1 will show in the browser, Component2 will not

### Expected result

Component2 shows in the browser

### Actual result

Component2 did not show in the browser

### Additional information

**VS Code Version**: 1.40

**SFDX CLI Version**: sfdx-cli/7.32.0 darwin-x64 node-v13.1.0

**OS and version**: OS X Catalina

**Comment by lcampos** [comment]
Closing since this issue has been fixed in the latest versions of the plugin. Thanks for providing feedback.
